In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
input_dir = os.path.join(r"C:\VY-Projects\sandag\Inputs")
output_dir = os.path.join(r"C:\VY-Projects\sandag\Inputs")

In [1]:
#mock up accessibilities file
df_acc = pd.read_csv(os.path.join(input_dir, "accessibilities.csv"))
df_clusters = pd.read_csv(os.path.join(input_dir, "taz_crosswalk.csv"))
df_mgra = pd.read_csv(os.path.join(input_dir, "mgra13_based_input2016.csv"), usecols = ["mgra", "taz"])

NameError: name 'pd' is not defined

In [5]:
#household and person file
df_hh = pd.read_csv(os.path.join(input_dir, "households.csv"))
df_per = pd.read_csv(os.path.join(input_dir, "persons.csv"))

In [6]:
df_hh.columns

Index(['hhid', 'household_serial_no', 'taz', 'mgra', 'hinccat1', 'hinc',
       'hworkers', 'veh', 'persons', 'hht', 'bldgsz', 'unittype', 'version',
       'poverty'],
      dtype='object')

In [8]:
df_per.columns

Index(['hhid', 'perid', 'household_serial_no', 'pnum', 'age', 'sex', 'miltary',
       'pemploy', 'pstudent', 'ptype', 'educ', 'grade', 'occen5', 'occsoc5',
       'indcen', 'weeks', 'hours', 'rac1p', 'hisp', 'version',
       'timeFactorWork', 'timeFactorNonWork'],
      dtype='object')

In [9]:
df_hh['taz'] = df_hh['taz'].map(dict_clusters)
df_hh['mgra'] = df_hh['taz']
df_hh.to_csv(os.path.join(output_dir, "households_mod.csv"), index = False)

In [7]:
#crosswalk mgra to taz to cluster id
dict_clusters = dict(zip(df_clusters['taz'], df_clusters['cluster_id']))

df_mgra['cluster_id'] = df_mgra['taz'].map(dict_clusters)
dict_mgra = dict(zip(df_mgra['mgra'], df_mgra['cluster_id']))

df_acc['cluster_id'] = df_acc['MGRA'].map(dict_mgra)

#delete the MGRA columns
df_acc = df_acc.drop(columns = "MGRA")

In [10]:
df_hh['taz'].nunique()

1694

In [11]:
df_hh['mgra'].nunique()

1694

In [12]:
df_hh.columns

Index(['hhid', 'household_serial_no', 'taz', 'mgra', 'hinccat1', 'hinc',
       'hworkers', 'veh', 'persons', 'hht', 'bldgsz', 'unittype', 'version',
       'poverty'],
      dtype='object')

In [8]:
# for iteration one

#accessibility fole for previous iteration
prev_iter_access = "accessibilities_mockup.csv"

if os.path.isfile(os.path.join(input_dir, prev_iter_access)):
    prev_iter_access = pd.read_csv(os.path.join(input_dir, "accessibilities_mockup.csv"))
else:
    raise Exception(f"The file {prev_iter_access} does not exist")

#accessbility file for current iteration
#curr_iter_access = "accessibilities_iter.csv"

#input household file
#input_household = "households.csv"

#input person file
#input_person = "persons.csv"

# List of Cluster IDs of study area
#study_area = [45, 60, 22, 100, 1500, 1800, 2000]

#
#output_hh_df

#sampled
#sample_rates_df

#list of values (columns in accessibility file) of compare
#compare_access_columns = ["NONMAN_AUTO", "NONMAN_TRANSIT", "NONMAN_NONMOTOR", "NONMAN_SOV_0"]

#deafult_sampling_rate = 0.25

#lower_bound_sampling_rate = 25
#upper_bound_sampling_rate = 100

In [9]:
prev_iter_access

,cluster_id,NONMAN_AUTO,NONMAN_TRANSIT,NONMAN_NONMOTOR,NONMAN_SOV_0,NONMAN_SOV_1,NONMAN_SOV_2,NONMAN_HOV_0,NONMAN_HOV_1,NONMAN_HOV_2,...,VISIT_SOV_2,DISCR_SOV_0,DISCR_SOV_1,DISCR_SOV_2,ATWORK_SOV_0,ATWORK_SOV_2,TOTAL_EMP,ATWORK_NM,ALL_HHS_TRANSIT,NONMAN_MAAS
0,13,10.941120,0.000000,1.602823,1.602823,12.941140,14.441120,12.021201,13.021170,12.521182,...,12.649410,2.340062,10.450376,11.949907,-3.789738,11.049300,13.667689,-3.789738,0.000000,7.971160
1,14,11.804790,0.000000,4.671034,4.671034,13.804895,15.304814,12.885084,13.884910,13.384971,...,13.517531,3.152909,11.228442,12.728194,1.022297,11.911700,14.521856,1.022297,0.000000,9.560310
2,15,11.693060,0.000000,1.730967,1.730967,13.693062,15.193060,12.772915,13.772902,13.272902,...,13.406712,4.220953,11.312122,12.811358,-3.681773,11.797810,14.448652,-3.681773,0.000000,9.167100
3,16,10.759110,0.000000,-0.733250,-0.733250,12.759116,14.259106,11.841804,12.841788,12.341795,...,12.460226,2.970919,10.623331,12.122769,0.000000,10.870240,13.454291,0.000000,0.000000,7.494940
4,17,8.896840,0.000000,-0.460320,-0.460320,10.896860,12.396850,9.977620,10.977600,10.477600,...,10.714860,6.724000,11.081995,12.569740,-4.519260,8.958700,11.568170,-4.519260,0.000000,5.387650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,2008,13.667279,12.000919,9.515948,11.635889,15.695947,17.173754,14.794333,15.775565,15.292323,...,15.254075,8.641674,12.926793,14.409600,8.311035,13.829848,16.411340,6.019748,10.979311,12.610143
1996,2009,13.379134,10.892465,9.489557,10.733252,15.393275,16.882311,14.486571,15.475522,14.983877,...,14.995807,7.726523,12.701980,14.194155,7.396862,13.526975,16.042168,6.076146,9.866993,12.103130
1997,2010,13.347528,9.771619,9.128490,10.123426,15.355557,16.849326,14.445829,15.439083,14.943846,...,14.908138,7.195832,12.604821,14.099729,6.881522,13.541718,16.218670,5.791417,8.707295,11.998752
1998,2011,13.642114,11.523937,9.768611,11.275115,15.661134,17.146396,14.754970,15.741054,15.252273,...,15.163798,8.223799,12.872445,14.361473,8.021857,13.834739,16.436617,6.452631,10.228478,12.543331
1999,2012,11.481372,1.723746,3.235600,4.297272,13.482826,14.981700,12.565756,13.564816,13.065684,...,13.104454,4.167490,10.951880,12.449830,-2.167092,11.621768,14.255094,-3.474608,1.533240,9.170830

In [ ]:
#dictionary

In [14]:
#changing the taz and mgra to new cluster ids
input_household_df = pd.read_csv(os.path.join(input_dir, input_household))
input_household_df["taz"] = input_household_df["taz"].map(dict_clusters)
input_household_df["mgra"] = input_household_df["taz"]
input_household_df["count"] = 1

In [15]:
taz_hh = input_household_df.groupby(["taz"])["count"].count().reset_index()

In [16]:
taz_hh

       taz  count
0       13    300
1       14    144
2       16     13
3       18    126
4       20      4
...    ...    ...
1689  2008   2795
1690  2009   1462
1691  2010   1164
1692  2011    894
1693  2012  11368

[1694 rows x 2 columns]

In [20]:
#sample households

if not os.path.isfile(os.path.join(curr_iter_access)):
    
    # true for first iteraion
    # sample 100% of households from study region
    # sample 25% of the households from rest of the region 

    taz_hh["sampling_rate"] = deafult_sampling_rate
    taz_hh.loc[taz_hh["taz"].isin(study_area), "sample_rate"] = 1
    
    sample_households = []
    
    for row in taz_hh.rows():
        df = input_household_df.loc[input_household["taz"] == row["taz"]]
        sampling_rate = row["sampling_rate"]
        df = df.sample(frac = default_sampling_rate, random_state = 1234)
        sample_households.append(df)
    
    #combine study are and non-study area households into single dataframe
    sample_households_df = pd.concat(sample_households)
    sample_households_df.to_csv(os.path.join(output_dir, "sample_households.csv"), index = False)
    
else:
    #true for second, third and fourth iteration
    curr_iter_access = pd.read_csv(os.path.join(input_dir, curr_iter_access))
    
    #compare accessibility columns
    compare_results = pd.DataFrame()

    for column in compare_access_columns.append("MGRA"):
        if column == "MGRA":
            compare_results[column] = prev_iter_access[column]
        else:
            compare_results[column] = (curr_iter_access[column] - prev_iter_access[column]).abs() # take absolute difference
        
    #Take row sums of all difference    
    compare_results["Total"] = compare_results[cols_to_sum].sum(axis = 1)
    
    #
    compare_results['sampling_rate'] = compare_results["Total"].clip(lower_bound_sampling_rate, upper_bound_sampling_rate)
    
    sample_households = []
    sample_rate_df = compare_results[["MGRA", "sampling_rate"]]
    sample_rate_df = sample_rate_df["sampling_rate"]/100
    sample_rate_df.loc[sample_rate_df["MGRA"].isin(study_area), "sampling_rate"] = 1 (#check back the order after tests)
    
    for row in sample_rate_df.rows():
        df = input_household_df.loc[input_household["taz"] == row["MGRA"]]
        sampling_rate = row["sampling_rate"]
        df = df.sample(frac = default_sampling_rate, random_state = 1234)
        sample_households.append(df)
        
    #combine study are and non-study area households into single dataframe
    sample_households_df = pd.concat(sample_households)
    sample_households_df.to_csv(os.path.join(output_dir, "sample_households.csv"), index = False)

In [53]:
compare_results

      NONMAN_AUTO  NONMAN_TRANSIT  NONMAN_NONMOTOR  NONMAN_SOV_0
0             0.0             0.0              0.0           0.0
1             0.0             0.0              0.0           0.0
2             0.0             0.0              0.0           0.0
3             0.0             0.0              0.0           0.0
4             0.0             0.0              0.0           0.0
...           ...             ...              ...           ...
1995          0.0             0.0              0.0           0.0
1996          0.0             0.0              0.0           0.0
1997          0.0             0.0              0.0           0.0
1998          0.0             0.0              0.0           0.0
1999          0.0             0.0              0.0           0.0

[2000 rows x 4 columns]

In [22]:
sample_households.shape

(302204, 14)

In [21]:
hh = pd.read_csv(os.path.join(input_dir, "households.csv"))
hh.columns

Index(['hhid', 'household_serial_no', 'taz', 'mgra', 'hinccat1', 'hinc',
       'hworkers', 'veh', 'persons', 'hht', 'bldgsz', 'unittype', 'version',
       'poverty'],
      dtype='object')

In [17]:
per = pd.read_csv(os.path.join(input_dir, "persons.csv"))
per.columns

Index(['hhid', 'perid', 'household_serial_no', 'pnum', 'age', 'sex', 'miltary',
       'pemploy', 'pstudent', 'ptype', 'educ', 'grade', 'occen5', 'occsoc5',
       'indcen', 'weeks', 'hours', 'rac1p', 'hisp', 'version',
       'timeFactorWork', 'timeFactorNonWork'],
      dtype='object')

In [ ]:
# final function

In [ ]:
prev_access_df = "accessibilities_mockup.csv" #created from previous model run
current_access_df = "accessibilities_iter.csv"
project_gdf = [45, 60, 22, 100, 1500, 1800, 2000] #list from clustered zones, study area
hh_df = "households.csv"
person_df = "persons.csv"
access_columns = ["NONMAN_AUTO", "NONMAN_TRANSIT", "NONMAN_NONMOTOR", "NONMAN_SOV_0"] #updated 
deafult_sampling_rate = 0.25 
lb_sampling_rate = 0.25 #updated based on testing
ub_sampling_rate = 1 #updated based on testing

In [ ]:
def intel_sample(
    input_dir,
    output_dir,
    prev_iter_access = prev_access_df, 
    curr_iter_access = current_access_df,
    study_area = project_gdf,
    input_household = hh_df,
    input_person = person_df,
    compare_access_columns = access_columns,
    default_sampling_rate,
    lower_bound_sampling_rate = lb_sampling_rate, #fix the values of this after some testing
    upper_bound_sampling_rate = ub_sampling_rate #fix the values of this after some testing
):
    
    if os.path.isfile(os.path.join(input_dir, prev_iter_access)):
        prev_iter_access = pd.read_csv(os.path.join(input_dir, "accessibilities_mockup.csv"))
    else:
        raise Exception(f"The file {prev_iter_access} does not exist")
        
    #changing the taz and mgra to new cluster ids
    input_household_df = pd.read_csv(os.path.join(input_dir, input_household))
    input_household_df["taz"] = input_household_df["taz"].map(dict_clusters)
    input_household_df["mgra"] = input_household_df["taz"]
    input_household_df["count"] = 1
    
    taz_hh = input_household_df.groupby(["taz"])["count"].count().reset_index()
    
    if not os.path.isfile(os.path.join(curr_iter_access)):
    
        # true for first iteraion
        # sample 100% of households from study region
        # sample 25% of the households from rest of the region 

        taz_hh["sampling_rate"] = deafult_sampling_rate
        taz_hh.loc[taz_hh["taz"].isin(study_area), "sample_rate"] = 1

        sample_households = []

        for row in taz_hh.rows():
            df = input_household_df.loc[input_household["taz"] == row["taz"]]
            sampling_rate = row["sampling_rate"]
            df = df.sample(frac = default_sampling_rate, random_state = 1234)
            sample_households.append(df)

        #combine study are and non-study area households into single dataframe
        sample_households_df = pd.concat(sample_households)
        sample_households_df.to_csv(os.path.join(output_dir, "sample_households.csv"), index = False)
    
    else:
        #true for second, third and fourth iteration
        curr_iter_access = pd.read_csv(os.path.join(input_dir, curr_iter_access))

        #compare accessibility columns
        compare_results = pd.DataFrame()

        for column in compare_access_columns.append("MGRA"):
            if column == "MGRA":
                compare_results[column] = prev_iter_access[column]
            else:
                compare_results[column] = (curr_iter_access[column] - prev_iter_access[column]).abs() # take absolute difference

        #Take row sums of all difference    
        compare_results["Total"] = compare_results[cols_to_sum].sum(axis = 1) #

        #
        compare_results['sampling_rate'] = compare_results["Total"].clip(lower_bound_sampling_rate, upper_bound_sampling_rate)

        sample_households = []
        sample_rate_df = compare_results[["MGRA", "sampling_rate"]]
        sample_rate_df = sample_rate_df["sampling_rate"]/100
        sample_rate_df.loc[sample_rate_df["MGRA"].isin(study_area), "sampling_rate"] = 1

        for row in sample_rate_df.rows():
            df = input_household_df.loc[input_household["taz"] == row["MGRA"]]
            sampling_rate = row["sampling_rate"]
            df = df.sample(frac = default_sampling_rate, random_state = 1234)
            sample_households.append(df)

        #combine study are and non-study area households into single dataframe
        sample_households_df = pd.concat(sample_households)
        sample_households_df.to_csv(os.path.join(output_dir, "sample_households.csv"), index = False)
        
        
    #select persons belonging to sampled households
    sample_hhids = list(sample_households_df["hhid"])
    persons_df = pd.read_csv(os.path.join(input_dir, input_person))
    sample_persons_df = persons_df.loc[persons_df["hhid"].isin(sample_hhids)]
    sample_persons_df.to_csv(os.path.join(output_dir, "sample_persons.csv"), index = False)